name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - r=4.0
  - plotly
  - dpylyr
  - ggplot2
  - reshape2
  - tidyverse
  - scikit_learn
  - stringr
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
